swagger: "2.0"
info:
  title: "ICICI Xpress Connect eCollection MIS API - RNVP"
  description: "eCollection MIS Intimation for RNVP Technologies Pvt. Ltd."
  termsOfService: ""
  contact:
    name: "RNVP Technologies Pvt Ltd."
    email: "funding@i2ifunding.com"
    x-mis-contact-email: 
      - "vaibhav@i2ifunding.com"
      - "abhinav@i2ifunding.com"
    url: "https://"
  license:
    name: ""
    url: "https://"
  version: "1.0.0"
host: "apiv1.i2ifunding.com"
basePath: "/api"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /intimate:
    post:
      tags: 
        - "eCollection"
      summary: Intimation.
      description: "MIS intimation."
      operationId: "Intimation"
      parameters:
        - description: "Intimation Notification."
          in: "body"
          name: "body"
          schema:
            $ref: "#/definitions/IntimationRequest"
      responses:
        '200':
          description: "Intimation Acknowledgment."
          schema:
            $ref: "#/definitions/IntimationResponse"
        400:
          description: "API request from sender application is not valid. One or more\
            \ mandatory fields were found missing from the request or were inconsistent."
          schema:
            $ref: "#/definitions/IntimationResponse"
        422:
          description: "API request from the sender application was understood but\
            \ declined as one or more mandatory business data fields were either missing\
            \ or had invalid data.'"
          schema:
            $ref: "#/definitions/IntimationResponse"
        500:
          description: "Server experienced an unexpected error that prevented\
            \ it from fulfilling the API request."
          schema:
            $ref: "#/definitions/IntimationResponse"
definitions:
  IntimationRequest:
    properties:
      client_code:
        type: "string"
        title: "Client Code"
        description: "Client Code - Virtual Code."
        minLength: 4
        maxLength: 4
        example: "3044"
      virtual_account_number:
        type: "string"
        title: "Virtual Account Number"
        description: "Unique actual virtual account no. of client."
        minLength: 20
        maxLength: 30
        example: "30450000000000245376"
      transaction_amount:
        type: "number"
        title: "Transaction Amount"
        description: "Transaction Amount."
        maxLength: 14
        pattern: "[0-9]{1,11}\\.[0-9]{2}"
        example: "10001.00"
      currency_code:
        type: "string"      
      payment_mode:
        type: "string"
        title: "Transaction Mode"
        description: "Payment Mode. NEFT: N, RTGS: R, FT: I, IMPS: O"
        minLength: 1
        maxLength: 1
        enum:
        - "NEFT"
        - "RTGS"
        - "IMPS"
        - "FT"
        example: "NEFT"
      transaction_id:
        type: "string"
      transaction_datetime:
        type: "string"       
      sender_name:
        type: "string"        
      sender_mobile_communication_number:
        type: "string"
      sender_account_number:
        type: "string"    
      client_account_number:
        type: "string"            
      sender_bank_name:
        type: "string"
      sender_ifsc_code:
        type: "string"  
      narration_1:
        type: "string"    
      transaction_id_type:
        type: "string"        
      request_id:
        type: "string"  
      request_datetime:
        type: "string"
    type: object 
  IntimationResponse:
    allOf:
    #- $ref: "#/definitions/IntimationRequest"
    - type: "object"
      properties:
        completion_code:
          type: "number"
          title: "completion code"
          description: "Decision point for collection. Recommended Values: 0 / 2."
          enum:
          - 0
          - 2
          example: 0
        reason_code:
          type: "string"
          title: "reason code"
          description: "reason code is mandatory in case the completion code received is 2 else blank value. The funds will be remitted to the originating bank."
          minLength: 0
          maxLength: 35
          example: " XCA00001E"
        message:
          type: "string"
          title: "message"
          description: "Contains the remarks when completion code is 0 or the rejection reason when completion code is 2"
          minLength: 0
          maxLength: 35
          example: "Sender Account Number and Sender Name mismatch."
      required: 
      - completion_code